name = "SimpleImageRegistration"
uuid = "429a002d-bc4d-4683-9383-b719270f290d"
authors = ["Galen Lynch <galen@galenlynch.com>"]
version = "0.1.1"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NNlibCUDA = "a00861dc-f156-4864-bf3c-e6376f28a68d"

[compat]
julia = "1.5"
CUDA = "3"
NNlib = "0.7"
NNlibCUDA = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
